# Generated by Django 3.2.13 on 2023-09-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=50)),
                ('launch_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=50)),
                ('launch_date', models.DateField()),
            ],
        ),
    ]
