# Generated by Django 3.2.13 on 2023-09-06 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appdoeduardo', '0002_distros'),
    ]

    operations = [
        migrations.AddField(
            model_name='distros',
            name='launch_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distros',
            name='processor',
            field=models.CharField(default=django.utils.timezone.now,
                                   max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[
                ('WIP',
                 'O desenvolvimento da funcionalidade está em progresso ativo, mas ainda não está pronto para testes mais amplos, uso ou distribuição'
                 ),
                ('linux-asahi',
                 'a funcionalidade é (relativamente) estável e disponível para uso no linux-asahi'
                 ),
                ('TBA',
                 'Não está sendo realizado trabalho ativo nesta funcionalidade no momento'
                 )
            ],
                                   default=django.utils.timezone.now,
                                   max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='features',
            name='version',
            field=models.CharField(choices=[('v1', '1.0'), ('v2', '2.0'),
                                            ('v3', '3.0')],
                                   default=django.utils.timezone.now,
                                   max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machines',
            name='available',
            field=models.CharField(default=django.utils.timezone.now,
                                   max_length=50),
            preserve_default=False,
        ),
    ]
