# Generated by Django 3.2.13 on 2023-09-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdoeduardo', '0003_auto_20230906_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='processor',
        ),
    ]
